#!/usr/bin/env bash
# ----------------------------------------------------------------------------------
# Project: GenX3-RCC
# File: cleanup
# ----------------------------------------------------------------------------------
# Purpose:
# Loads uv and runs the GenX3 environment cleanup.
# ----------------------------------------------------------------------------------
# Copyright (c) 2026 Christofanis Skordas, The University of Chicago
# ----------------------------------------------------------------------------------

module load uv

uv run genx-rcc clean
